### ISSUE TITLE
Version 1.2.2 doesn't have spring `get`

### ISSUE THREAD

**Issue by oliverisaac** [noqcks/gucci#24]
Please re-build and re-release to include the latest sprig templating features :)

https://github.com/Masterminds/sprig/commit/d4e8594bf4251d8417d4740709aaa82a726266a5

**Comment by oliverisaac** [comment]
@noqcks bumping this request

**Comment by oliverisaac** [comment]
@noqcks , bumping this again

**Comment by noqcks** [comment]
Sorry! I will look today!

**Comment by oliverisaac** [comment]
Hey @noqcks , I'm not sure the term for this, but could you push a build release for 1.2.4? The download command doesn't work because the artifacts aren't there:

<img width="912" alt="Screen Shot 2020-11-16 at 9 47 44 AM" src="https://user-images.githubusercontent.com/28768356/99275510-38e40000-27f1-11eb-89eb-056d9af8c499.png">

**Comment by noqcks** [comment]
Yeah, there was an issue with the travis-ci setup and the build failed.

Just pushed a new tag for 1.2.4 that should have the artifacts now.
