### ISSUE TITLE
[Feature Request] Set optional missing_key value for Template Options

### ISSUE THREAD

**Issue by kir4h** [noqcks/gucci#27]
Currently, `missing_key` template Option is hardcoded (https://github.com/noqcks/gucci/blob/master/gucci.go#L123).

It would be nice if this behaviour can be configured with any of the options available in the `Option` func (https://golang.org/pkg/text/template/#Template.Option).

In my scenario, I am defining a docker-compose template having a number of services, where each individual service has a set of properties but can be disabled. With current behaviour, I need to declare every single property even if the service is disabled.

I can work on it if you are open to PR (or work on it yourself if you prefer @noqcks )

Thanks!

**Comment by noqcks** [comment]
This sounds reasonable. Im open to contributions!

However, I think the default should still be `missingkey=error`
