### ISSUE TITLE
option to escape templating markers

### ISSUE THREAD

**Issue by Morriz** [noqcks/gucci#32]
Hi, in helmfile we are given the option to escape template markers with backtics like so:
```
{{`{{ function_in_some_other_template_language_using_same_markers }}`}}
```

Is this possible with gucci? Otherwise we would have to use dirty workarounds that prepare that output into env vars, which is not desired.

**Comment by noqcks** [comment]
yep, the same thing works in gucci

```
Start typing stuff {{ print "here" }}
{{ `{{ ignore this }}` }}
```
outputs
````
Start typing stuff here
{{ ignore this }}
```
