### ISSUE TITLE
Release 1.5.2, wrong 1.5.1 version shown

### ISSUE THREAD

**Issue by jfranzoi-gucci** [noqcks/gucci#40]
Hello @noqcks, just wanted to share that [release 1.5.2](/noqcks/gucci/releases/tag/1.5.2) is showing 1.5.1 with `--version`. Not a big issue I'd say 😂 

PS: I'd also take the opportunity to share with you I've been using `gucci` for our internal CI/CD tool in [GuccioGucci](https://github.com/GuccioGucci), see [here](https://github.com/GuccioGucci/yoke). What a perfect match with naming!

Regards,
Jacopo.

**Comment by noqcks** [comment]
Oh, my apologies for that! I didn't want to disturb the checksum, so I released a new version (1.5.3) with an accurate cli version output. 

It's awesome to hear you're making some use of it at Gucci 😂
