### ISSUE TITLE
Missing v in the url for the binary download

### ISSUE THREAD

**Issue by martinbozinovski** [noqcks/gucci#60]
2nd step is: wget -q "https://github.com/noqcks/gucci/releases/download/${VERSION}/gucci-v${VERSION}-darwin-amd64"
It is missing a v after download, and corrected step: 
wget -q https://github.com/noqcks/gucci/releases/download/v${VERSION}/gucci-v${VERSION}-darwin-amd64

**Comment by noqcks** [comment]
updated in https://github.com/noqcks/gucci/commit/31b3d70cc51f2d7f66da2658e4a44c31f0f6ba01

thanks for creating an issue 🙏
